apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argus
  template:
    metadata:
      labels:
        app: argus
    spec:
      containers:
      - name: argus
        image: argus-control:latest
